### PR TITLE
Add python assist wrap expression jython script plugin.

### PR DESCRIPTION
**Pull request by yohell**
Hey Fabio!

I'm not really fluent with github pull requests, but this references this old one of mine:

https://github.com/aptana/Pydev/pull/18

I made (some of :-) your proposed changes, so it now respects indent settings like you suggested. It only took me 4 years :-) 

I've had a ton of use for Pydev (and this plugin) over the years, so here's hoping you can have some use for the plugin as well.

Thanks for all your long, hard and good work with Pydev!

### CODE REVIEW

**Comment by fabioz** [comment]
Hi Yohell,

Thank you for the update... now, there's one thing, this is no longer the PyDev official repository... do you think you could update your local repo with the contents from the development branch from  https://github.com/fabioz/pydev and create a new pull request from there?

Note that if you feel it's hard for you, I can manually get it (but then it won't have your name on the commit)...

**Comment by yohell** [comment]
Well I can certainly try. Let me know if I got it right!

**Comment by sgtcoolguy** [comment]
Closing old PR that is breaking our build plugins on jennies (because the fork is gone?)

**Comment by yohell** [comment]
Yeah, we already got this code into https://github.com/fabioz/pydev. 

Cheers!

**Pull request closed without merging**
